---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
  memberOf:
    - "guests"
    - "digital-app-team"
    - "digital-database-team"
    - "digital-engineering-team"
    - "digital-microservices-team"
    - "digital-web-team"
    - "development"
    - "microservices-development"
    - "database-development"
    - "web-development"
    - "app-development"
    - "engineering"
    - "engineering-development"
    - "BIAN"
    - "account-management"
    - "bank-portfolio-treasury"
    - "buildings-equipment-facilities"
    - "business-analysis"
    - "business-commcontrol"
    - "cards"
    - "channel-specific"
    - "collateral-administration"
    - "consumer-services"
    - "corporate-financing-advisory-services"
    - "corporate-strategy"
    - "cross-channel"
    - "customer-management"
    - "document-management-archive"
    - "enterprise-services"
    - "external-agency"
    - "finance"
    - "human-resource-management"
    - "investment-management"
    - "it-management"
    - "knowledge-intellectual-property"
    - "loans-deposits"
    - "market-data"
    - "market-operations"
    - "marketing"
    - "models"
    - "operational-services"
    - "party"
    - "payments"
    - "product-management"
    - "regulations-compliance"
    - "sales"
    - "servicing"
    - "team.yaml trade-banking"
    - "wholesale-trading"
    - "platform-engineering"
