---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "servicing-event-history"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:cross-channel"
  system: "cross-channel"
  subcomponentOf:
    - "cross-channel"
  providesApis: []
  consumesApis: []
  dependsOn: []
