---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "session-dialogue"
  apiVersion: "1.0.0"
  description: cross-channel
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:cross-channel"
  system: "cross-channel"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
