---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "credit-management"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:trade-banking"
  system: "trade-banking"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
