---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "notional-pooling"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:trade-banking"
  system: "trade-banking"
  subcomponentOf:
  - "trade-banking"
  providesApis: []
  consumesApis: []
  dependsOn: []
