---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "leasing"
  apiVersion: "1.0.0"
  description: loans-deposits
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:loans-deposits"
  system: "loans-deposits"
  subcomponentOf: "loans-deposits"
  providesApis: []
  consumesApis: []
  dependsOn: []
