apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: document-management-archive
  description: document-management-archive
spec:
  type: team
  profile:
    email: document-management-archive@gmail.com
    picture: https://api.dicebear.com/5.x/adventurer/svg?seed=Felix
  parent: BIAN
  children: []