---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "loans-deposits"
  description: "loans-deposits"
spec:
  type: "team"
  profile:
    email: "loans-deposits@gmail.com"
    picture: "https://api.dicebear.com/5.x/adventurer/svg?seed=Felix"
  parent: "BIAN"
  children: []
