---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "account-management"
  description: "account-management"
spec:
  type: "team"
  profile:
    email: "account-management@gmail.com"
    picture: "https://api.dicebear.com/5.x/adventurer/svg?seed=Felix"
  parent: "BIAN"
  children: []
