apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: trade-banking
  description: trade-banking
spec:
  type: team
  profile:
    email: trade-banking@gmail.com
    picture: https://api.dicebear.com/5.x/adventurer/svg?seed=Felix
  parent: BIAN
  children: []