apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: it-management
  description: it-management
spec:
  type: team
  profile:
    email: it-management@gmail.com
    picture: https://api.dicebear.com/5.x/adventurer/svg?seed=Felix
  parent: BIAN
  children: []