apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: marketing
  description: marketing
spec:
  type: team
  profile:
    email: marketing@gmail.com
    picture: https://api.dicebear.com/5.x/adventurer/svg?seed=Felix
  parent: BIAN
  children: []