apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: database-development
  description: database-development
spec:
  type: team
  profile:
    email: database-development@gmail.com
    picture: https://api.dicebear.com/5.x/adventurer/svg?seed=Felix
  parent: digital
  children: []
