---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "testing"
  description: "testing"
spec:
  type: "team"
  profile:
    email: "testing@gmail.com"
    picture: "https://api.dicebear.com/5.x/adventurer/svg?seed=Felix"
  parent: "digital"
  children: []
