---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "marketing"
  title: "Marketing group"
  description: "The marketing sub-department"
spec:
  type: "sub-department"
  profile:
    displayName: "Marketing Office"
    email: "roadie-marketing@example.com"
  parent: "infrastructure"
  children: []
