---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "internal-developer-platform"
  description: "The internal-developer-platform organization"
  links:
    - url: "https://github.com/rock-hu/devx"
      title: "Website"
    - url: "https://github.com/rock-hu/developer-platform-manifests"
      title: "Intranet"
spec:
  type: "organization"
  profile:
    displayName: "internal-developer-platform"
    email: "info@internal-developer-platform.com"
    picture: "https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25"
  children:
    - "infrastructure"
    - "digital"
    - "marketing"
