---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "lead-opportunity-management"
  apiVersion: "1.0.0"
  description: sales
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:sales"
  system: "sales"
  subcomponentOf: "sales"
  providesApis: []
  consumesApis: []
  dependsOn: []
