---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "correspondent-bank-directory"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:external-agency"
  system: "external-agency"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
