---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "product-broker-agreement"
  apiVersion: "1.0.0"
  description: external-agency
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:external-agency"
  system: "external-agency"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
