---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "product-design"
  apiVersion: "1.0.0"
  description: product-management
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:product-management"
  system: "product-management"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
