---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "market-analysis"
  apiVersion: "1.0.0"
  description: business-analysis
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:business-analysis"
  system: "business-analysis"
  subcomponentOf: "business-analysis"
  providesApis: []
  consumesApis: []
  dependsOn: []
