---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "investment-portfolio-planning"
  apiVersion: "1.0.0"
  description: investment-management
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:investment-management"
  system: "investment-management"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
