# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: compliance-reporting
  apiVersion: 
  description: 
spec:
  type: service #service,website,library
  lifecycle: production #experimental,production,deprecated
  owner: group:regulations-compliance
  system: regulations-compliance
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
