---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "financial-accounting"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:regulations-compliance"
  system: "regulations-compliance"
  subcomponentOf:
  - "regulations-compliance"
  providesApis: []
  consumesApis: []
  dependsOn: []
