---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "regulatory-reporting"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:regulations-compliance"
  system: "regulations-compliance"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
