---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "counterparty-administration"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:market-data"
  system: "market-data"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
