---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "information-provider-operation"
  apiVersion: "1.0.0"
  description: market-data
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:market-data"
  system: "market-data"
  subcomponentOf: "market-data"
  providesApis: []
  consumesApis: []
  dependsOn: []
