---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "legal-entity-directory"
  apiVersion: "1.0.0"
  description: party
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:party"
  system: "party"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
