---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "fixed-asset-register"
  apiVersion: "1.0.0"
  description: enterprise-services
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:enterprise-services"
  system: "enterprise-services"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
