---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "legal-advisory"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:enterprise-services"
  system: "enterprise-services"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
