---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "advertising"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:marketing"
  system: "marketing"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
