---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "prospect-campaign-design"
  apiVersion: "1.0.0"
  description: marketing
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:marketing"
  system: "marketing"
  subcomponentOf: "marketing"
  providesApis: []
  consumesApis: []
  dependsOn: []
