---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "asset-securitization"
  apiVersion: "1.0.0"
  description: bank-portfolio-treasury
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:bank-portfolio-treasury"
  system: "bank-portfolio-treasury"
  subcomponentOf: "bank-portfolio-treasury"
  providesApis: []
  consumesApis: []
  dependsOn: []
