---
apiVersion: "backstage.io/v1alpha1"
kind: "Location"
metadata:
  name: "all-components"
  description: "A collection of all Backstage example components"
spec:
  targets:
    # - "./components/*.yaml"

    - "./components/service/experimental/*.yaml"

    - "./components/service/production/account-management/*.yaml"
    - "./components/service/production/bank-portfolio-treasury/*.yaml"
    - "./components/service/production/buildings-equipment-facilities/*.yaml"
    - "./components/service/production/business-analysis/*.yaml"
    - "./components/service/production/business-commcontrol/*.yaml"
    - "./components/service/production/cards/*.yaml"
    - "./components/service/production/channel-specific/*.yaml"
    - "./components/service/production/collateral-administration/*.yaml"
    - "./components/service/production/consumer-services/*.yaml"
    - "./components/service/production/corporate-financing-advisory-services/*.yaml"
    - "./components/service/production/corporate-strategy/*.yaml"
    - "./components/service/production/cross-channel/*.yaml"
    - "./components/service/production/customer-management/*.yaml"
    - "./components/service/production/document-management-archive/*.yaml"
    - "./components/service/production/enterprise-services/*.yaml"
    - "./components/service/production/external-agency/*.yaml"
    - "./components/service/production/finance/*.yaml"
    - "./components/service/production/human-resource-management/*.yaml"
    - "./components/service/production/investment-management/*.yaml"
    - "./components/service/production/it-management/*.yaml"
    - "./components/service/production/knowledge-intellectual-property/*.yaml"
    - "./components/service/production/loans-deposits/*.yaml"
    - "./components/service/production/market-data/*.yaml"
    - "./components/service/production/market-operations/*.yaml"
    - "./components/service/production/marketing/*.yaml"
    - "./components/service/production/models/*.yaml"
    - "./components/service/production/operational-services/*.yaml"
    - "./components/service/production/party/*.yaml"
    - "./components/service/production/payments/*.yaml"
    - "./components/service/production/product-management/*.yaml"
    - "./components/service/production/regulations-compliance/*.yaml"
    - "./components/service/production/sales/*.yaml"
    - "./components/service/production/servicing/*.yaml"
    - "./components/service/production/trade-banking/*.yaml"
    - "./components/service/production/wholesale-trading/*.yaml"
