---
apiVersion: "backstage.io/v1alpha1"
kind: "Location"
metadata:
  name: "all-openapis"
  description: "A collection of all APIs"
spec:
  targets:
    - "./openapis/*.yaml"
    - "./openapis/**/*.yaml"
