---
apiVersion: "backstage.io/v1alpha1"
kind: "Location"
metadata:
  name: "all-openapis"
  description: "A collection of all Backstage example APIs"
spec:
  owner: "group:engineering"
  targets:
    - "./openapis/*.yaml"
