---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "organization-direction"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:business-commcontrol"
  system: "business-commcontrol"
  subcomponentOf:
    - "business-commcontrol"
  providesApis: []
  consumesApis: []
  dependsOn: []
