---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "ach-operations"
  apiVersion: "1.0.0"
  description: payments
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:payments"
  system: "payments"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
