---
apiVersion: "backstage.io/v1alpha1"
kind: "Domain"
metadata:
  name: "bank-portfolio-treasury"
  description: "everything related to bank-portfolio-treasury"
spec:
  owner: "group:bank-portfolio-treasury"
