apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: buildings-equipment-facilities
  description: everything related to buildings-equipment-facilities
spec:
  owner: group:buildings-equipment-facilities