apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: collateral-administration
  description: everything related to collateral-administration
spec:
  owner: group:collateral-administration