apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: corporate-financing-advisory-services
  description: everything related to corporate-financing-advisory-services
spec:
  owner: group:corporate-financing-advisory-services