---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "trade-price-reporting"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:market-operations"
  system: "market-operations"
  subcomponentOf:
    - "market-operations"
  providesApis: []
  consumesApis: []
  dependsOn: []
