---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "unit-trust-administration"
  apiVersion: "1.0.0"
  description: market-operations
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:market-operations"
  system: "market-operations"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
