---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "issued-device-administration"
  apiVersion: "1.0.0"
  description: operational-services
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:operational-services"
  system: "operational-services"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
