---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "advanced-voice-services-management"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:channel-specific"
  system: "channel-specific"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
