---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "ebranch-management"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:channel-specific"
  system: "channel-specific"
  subcomponentOf:
  - "channel-specific"
  providesApis: []
  consumesApis: []
  dependsOn: []
