---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "accounts-receivable"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:account-management"
  system: "account-management"
  subcomponentOf:
  - "account-management"
  providesApis: []
  consumesApis: []
  dependsOn: []
