---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "securities-position-keeping"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:account-management"
  system: "account-management"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
