---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "brokered-product"
  apiVersion: "1.0.0"
  description: consumer-services
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:consumer-services"
  system: "consumer-services"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
