---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "collections"
  apiVersion: "1.0.0"
  description: collateral-administration
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:collateral-administration"
  system: "collateral-administration"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
