---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "it-standards-guidelines"
  apiVersion: "1.0.0"
  description: it-management
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:it-management"
  system: "it-management"
  subcomponentOf: "it-management"
  providesApis: []
  consumesApis: []
  dependsOn: []
