---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "systems-help-desk"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:it-management"
  system: "it-management"
  subcomponentOf:
  - "it-management"
  providesApis: []
  consumesApis: []
  dependsOn: []
