---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "customer-agreement"
  apiVersion: "1.0.0"
  description: customer-management
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:customer-management"
  system: "customer-management"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
