---
apiVersion: "backstage.io/v1alpha1"
kind: "Domain"
metadata:
  name: "account-access-consents"
  description: "everything related to account-access-consents"
spec:
  owner: "microservices-development"
