---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "program-trading"
  apiVersion: "1.0.0"
  description: "program-trading"
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:wholesale-trading"
  system: "wholesale-trading"
  subcomponentOf: "wholesale-trading"
  providesApis: []
  consumesApis: []
  dependsOn: []
