# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: suitability-checking
  apiVersion: 
  description: 
spec:
  type: service #service,website,library
  lifecycle: production #experimental,production,deprecated
  owner: group:wholesale-trading
  system: wholesale-trading
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
