---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "openbanking-website"
spec:
  type: "website"
  lifecycle: "experimental"
  owner: "web-development"
  system: "openbanking"
  providesApis:
  - "account-info"
  - "confirmation-funds"
  - "event-notifications"
  - "events"
  - "payment-initiation"
  - "vrp"
