# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parties-services
  apiVersion: 1.0.0
  description: parties-services
spec:
  type: service #service,website,library
  lifecycle: experimental #experimental,production,deprecated
  owner: group:microservices-development
  system: openbanking-aisp
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
