---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "transactions-services"
  apiVersion: "1.0.0"
  description: "transactions-services"
spec:
  type: "service"
  lifecycle: "experimental"
  owner: "group:microservices-development"
  system: "openbanking-aisp"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
