---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "transactions-services"
  apiVersion: "1.0.0"
  description: "transactions-services"
  annotations:
    backstage.io/code-coverage: enabled
    github.com/project-slug: "rock-hu/transactions-services"
    sonarqube.org/project-key: "internal-developer-platform/transactions-services"
spec:
  type: "service"
  lifecycle: "experimental"
  owner: "group:microservices-development"
  system: "openbanking-aisp"
  providesApis: []
  consumesApis: []
  dependsOn: []
