---
apiVersion: "backstage.io/v1alpha1"
kind: "Location"
metadata:
  name: "bian-semantic"
  description: "A collection of bian-semantic APIs"
spec:
  owner: "group:engineering"
  targets:
    - "./bian-semantic/*.yaml"
