---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "events"
  description: "OpenBankingUK - Events API"
  tags:
    - "OpenBankingUK"
    - "OBIE"
  annotations:
    backstage.io/code-coverage: enabled
    backstage.io/definition-at-location: "url:https://raw.githubusercontent.com/OpenBankingUK/read-write-api-specs/v3.1.10/dist/openapi/events-openapi.yaml"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "group:microservices-development"
  definition:
    $text: "https://raw.githubusercontent.com/OpenBankingUK/read-write-api-specs/v3.1.10/dist/openapi/events-openapi.yaml"
