---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "contribution-models"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:models"
  system: "models"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
