openapi: 3.0.0
info:
  title: Events API Specification - ASPSP Endpoints
  description: >-
    OpenAPI for Events (Subscription & Aggregated Polling) API Specification -
    ASPSP Endpoints
  termsOfService: https://www.openbanking.org.uk/terms
  contact:
    name: Service Desk
    email: ServiceDesk@openbanking.org.uk
  license:
    name: open-licence
    url: https://www.openbanking.org.uk/open-licence
  version: 4.0.0
paths:
  /event-subscriptions_{EventSubscriptionId}:
    $ref: paths/event-subscriptions_{EventSubscriptionId}.yaml
  /event-subscriptions:
    $ref: paths/event-subscriptions.yaml
  /events:
    $ref: paths/events.yaml
