openapi: 3.0.0
info:
  title: Events API Specification - ASPSP Endpoints
  description: >-
    OpenAPI for Events (Subscription & Aggregated Polling) API Specification -
    ASPSP Endpoints
  termsOfService: https://www.openbanking.org.uk/terms
  contact:
    name: Service Desk
    email: ServiceDesk@openbanking.org.uk
  license:
    name: open-licence
    url: https://www.openbanking.org.uk/open-licence
  version: 4.0.0
paths:
  /event-subscriptions:
    $ref: paths/event-subscriptions.yaml
  /event-subscriptions/{EventSubscriptionId}:
    $ref: paths/event-subscriptions_{EventSubscriptionId}.yaml
  /events:
    $ref: paths/events.yaml
servers:
  - url: /open-banking/v3.1
components:
  securitySchemes:
    TPPOAuth2Security:
      type: oauth2
      description: TPP client credential authorisation flow with the ASPSP
      flows:
        clientCredentials:
          tokenUrl: https://authserver.example/token
          scopes:
            accounts: Ability to receive events associated with Accounts information
            fundsconfirmations: Ability to receive events associated with confirmation of funds
            payments: Ability to receive events associated with payments
