---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "building-maintenance"
  apiVersion: "1.0.0"
  description: buildings-equipment-facilities
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:buildings-equipment-facilities"
  system: "buildings-equipment-facilities"
  subcomponentOf: "buildings-equipment-facilities"
  providesApis: []
  consumesApis: []
  dependsOn: []
