---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "building-maintenance"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:buildings-equipment-facilities"
  system: "buildings-equipment-facilities"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
