---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "products-services-direction"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:corporate-strategy"
  system: "corporate-strategy"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
