---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "management-manual"
  apiVersion: "1.0.0"
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:knowledge-intellectual-property"
  system: "knowledge-intellectual-property"
  subcomponentOf:
    - "knowledge-intellectual-property"
  providesApis: []
  consumesApis: []
  dependsOn: []
