---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "human-resources-direction"
  apiVersion: "1.0.0"
  description: human-resource-management
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:human-resource-management"
  system: "human-resource-management"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
