openapi: 3.0.0
info:
  title: Payment Initiation API
  description: Swagger for Payment Initiation API Specification
  termsOfService: https://www.openbanking.org.uk/terms
  contact:
    name: Service Desk
    email: ServiceDesk@openbanking.org.uk
  license:
    name: open-licence
    url: https://www.openbanking.org.uk/open-licence
  version: 4.0.0
paths:
  /file-payment-consents_{ConsentId}_file:
    $ref: paths/file-payment-consents_{ConsentId}_file.yaml
  /file-payment-consents_{ConsentId}:
    $ref: paths/file-payment-consents_{ConsentId}.yaml
  /file-payment-consents:
    $ref: paths/file-payment-consents.yaml
  /file-payments_{FilePaymentId}_payment-details:
    $ref: paths/file-payments_{FilePaymentId}_payment-details.yaml
  /file-payments_{FilePaymentId}_report-file:
    $ref: paths/file-payments_{FilePaymentId}_report-file.yaml
  /file-payments_{FilePaymentId}:
    $ref: paths/file-payments_{FilePaymentId}.yaml
  /file-payments:
    $ref: paths/file-payments.yaml
