openapi: 3.0.0
info:
  title: Payment Initiation API
  description: Swagger for Payment Initiation API Specification
  termsOfService: https://www.openbanking.org.uk/terms
  contact:
    name: Service Desk
    email: ServiceDesk@openbanking.org.uk
  license:
    name: open-licence
    url: https://www.openbanking.org.uk/open-licence
  version: 4.0.0
paths:
  /international-payment-consents_{ConsentId}_funds-confirmation:
    $ref: paths/international-payment-consents_{ConsentId}_funds-confirmation.yaml
  /international-payment-consents_{ConsentId}:
    $ref: paths/international-payment-consents_{ConsentId}.yaml
  /international-payment-consents:
    $ref: paths/international-payment-consents.yaml
  /international-payments_{InternationalPaymentId}_payment-details:
    $ref: paths/international-payments_{InternationalPaymentId}_payment-details.yaml
  /international-payments_{InternationalPaymentId}:
    $ref: paths/international-payments_{InternationalPaymentId}.yaml
  /international-payments:
    $ref: paths/international-payments.yaml
