name: manifests-groups
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/manifests-groups.yaml"
      - "manifests/groups/**"
jobs:
  validate-entity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install -g @roadiehq/backstage-entity-validator
      - run: yarn install
      - run: yarn manifests-groups