---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "servicing-mandate"
  apiVersion: "1.0.0"
  description: servicing
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:servicing"
  system: "servicing"
  # subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
