---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "servicing-order"
  apiVersion: null
  description: null
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:servicing"
  system: "servicing"
  subcomponentOf: []
  providesApis: []
  consumesApis: []
  dependsOn: []
